# Generated by Django 6.0.1 on 2026-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('role', models.CharField(max_length=30, verbose_name='Rôle')),
                ('nom_entreprise', models.CharField(max_length=30, verbose_name="Nom de l'entreprise")),
                ('description', models.TextField(verbose_name='Description')),
                ('type_de_contrat', models.CharField(max_length=30, verbose_name='Type de contrat')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=50, verbose_name='Ville')),
                ('pays', models.CharField(max_length=50, verbose_name='Pays')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
            },
        ),
        migrations.CreateModel(
            name='PriseDeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=70, verbose_name='Nom complet')),
                ('objet', models.CharField(max_length=30, verbose_name='Objet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Prise de contact',
                'verbose_name_plural': 'Prises de contact',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(verbose_name='Résumé du projet')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre')),
                ('image', models.CharField(max_length=50, verbose_name='Image')),
                ('lien', models.CharField(max_length=50, verbose_name='Lien')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_platforme', models.CharField(max_length=30, verbose_name='Nom de la plateforme')),
                ('lien', models.URLField(verbose_name='Lien')),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom du service')),
                ('details', models.TextField(verbose_name='Détails')),
                ('type_de_service', models.CharField(max_length=30, verbose_name='Type de service')),
                ('outils', models.CharField(max_length=100, verbose_name='Outils')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
