# Generated by Django 6.0.1 on 2026-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='experience_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='localisation_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prise_de_contact_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='projet_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='reseau_social_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='service_utilisateur',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='lien_cv',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien CV'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_de_profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
